version: "2.1"

services:

  loragtwpktfwd:
    restart: always
    build:
      context: loragtwpktfwd
      args:
        - LORA_UDP=1680
        - MINER_URL=helium-miner
    privileged: true

  helium-miner:
    restart: always
    image: quay.io/team-helium/miner:miner-arm64_2020.09.04.0_GA
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - 'miner-data:/var/data'
      - 'miner-log:/var/log/miner'
    environment:
      - 'REGION_OVERRIDE=US915'

volumes:
  miner-data:
  miner-log:
